config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  root to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @message = current_user.messages.build
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/shared_helper.rb
module SharedHelper
  def need_current_tab_class?(hole)
    (hole ? 'active show' : '')
  end
end

app/views/dashboard/index.html.erb
<%= render 'messages/form', message: @message %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hey - Chat2me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

  </head>

  <body class="bg-light">
    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
          width="72" height="72">
        <h2>Hey - Chat2Me</h2>
        <p class="lead">Hey! This is the easier way to chat with me!</p>
      </div>
      <div class="row">
        <%= render  "messages/index" %>
        <div class="col-md-8 order-md-1">
          <%= render 'shared/tabs' %>
          <div class="col-md-12 order-md-1" id="content">
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="test" role="tabpanel" aria-labelledby="test-tab">
              <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<form class="needs-validation" novalidate="">
  <div class="row">
    <div class="col-md-6 mb-3">
      <label for="username">Instagram user</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">@</span>
        </div>
        <input type="text" class="form-control" id="instagram" placeholder="just your instagram" required="">
        <div class="invalid-feedback" style="width: 100%;">
          Your instagram is required.
        </div>
      </div>
    </div>

    <div class="col-md-6 mb-3">
      <label for="email">Email</span></label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">@</span>
        </div>
        <input type="text" class="form-control" id="instagram" placeholder="just your instagram" required="">
        <div class="invalid-feedback" style="width: 100%;">
          Your instagram is required.
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mb-3">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" placeholder="" value="" required="">
      <div class="invalid-feedback">
        Valid password is required.
      </div>
    </div>
    <div class="col-md-6 mb-3">
      <label for="passwordConfirmation">Password Confirmation</label>
      <input type="password" class="form-control" id="passwordConfirmation" placeholder="" value="" required="">
      <div class="invalid-feedback">
        Valid password confirmation is required.
      </div>
    </div>
  </div>
  <hr class="mb-4">
  <div class="row">
    <div class="col-md-6 mb-3">
      <label for="firstName">First name</label>
      <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
      <div class="invalid-feedback">
        Valid first name is required.
      </div>
    </div>
    <div class="col-md-6 mb-3">
      <label for="lastName">Last name</label>
      <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
      <div class="invalid-feedback">
        Valid last name is required.
      </div>
    </div>
  </div>
  <button class="btn btn-info btn-lg btn-block" type="submit">
    <i class="fas fa-user-plus"></i>
    Sign Up
  </button>
</form>

app/views/messages/_index.html.erb
<div class="col-md-4 order-md-2 mb-4">
  <h6 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Messages in hour 6AM to 7AM</span>
    <span class="badge badge-secondary badge-pill">300</span>
  </h6>
  <ul class="list-group mb-3">
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div class="text-success">
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">@geovanni_cole</h6>
        <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
      </div>
    </li>
  </ul>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h6 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Messages in hour 6AM to 7AM</span>
  <span class="badge badge-secondary badge-pill">300</span>
</h6>
<ul class="list-group mb-3">
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div class="text-success">
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">@geovanni_cole</h6>
      <small class="text-muted">Maxime praesentium sit. Veritatis...</small>
    </div>
  </li>
</ul>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/shared/_tabs.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
<% unless user_signed_in? %>
  <li class="nav-item">
    <a class="nav-link <%= need_current_tab_class?(controller_name == 'sessions') %>" id="login-tab" href="<%=new_user_session_path %>" role="tab" aria-controls="login" aria-selected="<%= need_current_tab_class?(controller_name == 'sessions') %>">Login In</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= need_current_tab_class?(controller_name == 'registrations') %>" id="sign-up-tab" href="<%= new_user_registration_path %>" role="tab" aria-controls="sign-up" aria-selected="<%= need_current_tab_class?(controller_name == 'registrations')%>">Sign Up</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= need_current_tab_class?(controller_name == 'passwords') %>%" id="forgot-password-tab" href="#forgot-password" role="tab" aria-controls="forgot-password" aria-selected="<%= need_current_tab_class?(controller_name == 'passwords') %>">Forget Password?</a>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Dashboard', root_path, class: need_current_tab_class?(controller_name == 'dashboard'), id: "dashboard-in-tab", 'data-toggle': "tab", 'role': "tab", 'aria-controls': "sign-in"  %>
  </li>

  <li class="nav-item">
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: need_current_tab_class?(false), id: "log-out-tab", 'data-toggle': "tab", 'role': "tab", 'aria-controls': "log-out"  %>
  </li>
<% end %>
</ul>